# -*- coding: utf-8 -*-
import json

with open('data-zh.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

# Batch 13 - remaining 台東, 雲林, 澎湖, 金馬
updates = [
    # === 台東 remaining ===
    {"city":"台東","index":4,"dishes":[{"name":"個人鍋","desc":"小牧鍋Minimoo台東新生店，台東人氣個人小火鍋"}]},
    {"city":"台東","index":5,"dishes":[{"name":"快煮鍋","desc":"迪迪加快煮鍋，台東平價快煮鍋物"}]},
    {"city":"台東","index":6,"dishes":[{"name":"電力公司","desc":"路易奇電力公司台東電廠，台東特色咖啡簡餐"}]},
    {"city":"台東","index":7,"dishes":[{"name":"藝文咖啡","desc":"艾蘭哥爾藝文咖啡館，台東藝文咖啡廳"}]},
    {"city":"台東","index":8,"dishes":[{"name":"癒室","desc":"癒室，台東特色咖啡甜點店"}]},
    {"city":"台東","index":10,"dishes":[{"name":"茶園麵店","desc":"天來茶園鹿野高台麵店，台東鹿野茶園麵食"}]},
    {"city":"台東","index":20,"dishes":[{"name":"炭火燒肉","desc":"井碳吉炭火燒肉餐廳，台東人氣燒肉店"}]},
    {"city":"台東","index":22,"dishes":[{"name":"鍋物","desc":"八方悅鍋物台東店，台東人氣鍋物"}]},
    {"city":"台東","index":23,"dishes":[{"name":"日式鍋物","desc":"聚日式鍋物台東秀泰店，台東秀泰商場內"}]},
    {"city":"台東","index":30,"dishes":[{"name":"早午餐","desc":"荳荳阿稼早午餐，台東人氣早午餐店"}]},
    {"city":"台東","index":41,"dishes":[{"name":"咖啡甜點","desc":"双亭院咖啡餐食甜點，台東特色咖啡廳"}]},
    {"city":"台東","index":42,"dishes":[{"name":"絲綢咖啡","desc":"絲綢咖啡大溪社區入口處，台東海線咖啡"}]},
    {"city":"台東","index":43,"dishes":[{"name":"溫泉園區","desc":"紅葉谷綠能溫泉園區，台東延平溫泉體驗"}]},
    {"city":"台東","index":56,"dishes":[{"name":"義式料理","desc":"義回生餓回熟one two pasta，台東義式料理人氣店"}]},
    {"city":"台東","index":61,"dishes":[{"name":"海草冰","desc":"綠島海草冰，綠島必吃特色冰品"}]},
    {"city":"台東","index":69,"dishes":[{"name":"石頭涮涮鍋","desc":"養鍋Yang Guo石頭涮涮鍋台東光明店，台東人氣鍋物"}]},
    {"city":"台東","index":70,"dishes":[{"name":"湯滷","desc":"潮味決湯滷專門店台東中華分社，台東特色湯滷"}]},
    {"city":"台東","index":71,"dishes":[{"name":"日式定食","desc":"京厚屋台東更生店，台東日式定食人氣店"}]},
    {"city":"台東","index":72,"dishes":[{"name":"咖啡民宿","desc":"薄荷巴黎Coffee House台東，台東咖啡民宿"}]},
    {"city":"台東","index":78,"dishes":[{"name":"古早味小吃","desc":"台東知本東益古早味小吃，台東知本必吃"}]},
    {"city":"台東","index":82,"dishes":[{"name":"日式料理","desc":"初心四季料理，台東精緻日式料理"}]},
    {"city":"台東","index":95,"dishes":[{"name":"景觀咖啡","desc":"月亮彎彎景觀咖啡，台東鹿野高台夜景咖啡"}]},
    {"city":"台東","index":99,"dishes":[{"name":"竹屋餐廳","desc":"綠島竹屋餐廳，綠島必吃海鮮料理"}]},
    {"city":"台東","index":100,"dishes":[{"name":"黑糖海草冰","desc":"綠島小叮噹黑糖海草冰，綠島必吃冰品"}]},
    {"city":"台東","index":118,"dishes":[{"name":"炙燒丼飯","desc":"牛匠太郎x直火炙燒丼飯台東店，台東人氣丼飯"}]},
    {"city":"台東","index":119,"dishes":[{"name":"鯊魚料理","desc":"鯊魚黑幫餐廳成功店，台東成功特色鯊魚料理"}]},
    {"city":"台東","index":120,"dishes":[{"name":"素食","desc":"舒食男孩，台東人氣素食餐廳"}]},
    {"city":"台東","index":124,"dishes":[{"name":"火鍋","desc":"拾鑶台灣味火鍋台東店，台東人氣火鍋"}]},
    {"city":"台東","index":125,"dishes":[{"name":"火鍋","desc":"千葉火鍋台東尊爵館，台東高人氣火鍋吃到飽"}]},
    {"city":"台東","index":126,"dishes":[{"name":"日式燒肉","desc":"燒肉MEN YAKINIKU.MEN，台東日式燒肉親子友善"}]},
    {"city":"台東","index":133,"dishes":[{"name":"海景咖啡","desc":"藍色海灣Bluebayou，台東海景咖啡必去"}]},
    {"city":"台東","index":136,"dishes":[{"name":"酒場","desc":"雷門酒場，台東人氣日式酒場"}]},
    {"city":"台東","index":139,"dishes":[{"name":"村長的家","desc":"鐵花村長的家，台東鐵花村特色咖啡"}]},
    {"city":"台東","index":174,"dishes":[{"name":"鬼頭刀魚乾","desc":"成功鬼頭刀魚乾，台東成功必買伴手禮"}]},
    {"city":"台東","index":175,"dishes":[{"name":"金剛大道小吃","desc":"長濱金剛大道周邊小吃，台東長濱必吃"}]},
    {"city":"台東","index":176,"dishes":[{"name":"茶自點","desc":"茶自點台東旗艦店，台東人氣茶飲簡餐"}]},
    {"city":"台東","index":177,"dishes":[{"name":"美食堂","desc":"鐵花小路美食堂，台東鐵花村美食"}]},
    {"city":"台東","index":178,"dishes":[{"name":"牛排","desc":"歐鄉牛排館台東店，台東老牌牛排館"}]},
    {"city":"台東","index":183,"dishes":[{"name":"火鍋","desc":"湯蒸火鍋台東新生店，台東人氣蒸氣火鍋"}]},
    {"city":"台東","index":184,"dishes":[{"name":"火鍋","desc":"火鍋世家台東新生店，台東人氣火鍋連鎖"}]},
    {"city":"台東","index":185,"dishes":[{"name":"輕燒肉","desc":"打鐵火鍋輕燒肉，台東火鍋燒肉雙享受"}]},
    {"city":"台東","index":186,"dishes":[{"name":"牛排","desc":"來來牛排台東店，台東老牌牛排館"}]},
    {"city":"台東","index":190,"dishes":[{"name":"早餐","desc":"初早餐，台東人氣早午餐店"}]},
    {"city":"台東","index":194,"dishes":[{"name":"水果珍奶","desc":"果珍濃台東水果珍奶，台東特色水果飲"}]},
    {"city":"台東","index":206,"dishes":[{"name":"水果冰棒","desc":"春一枝鹿野76水果冰棒，台東誠信商店冰棒"}]},
    {"city":"台東","index":212,"dishes":[{"name":"社區咖啡","desc":"墾墨咖啡Community Cafe，台東社區咖啡廳"}]},
    {"city":"台東","index":218,"dishes":[{"name":"豆花","desc":"寶桑豆花，台東必吃古早味豆花"}]},
    {"city":"台東","index":220,"dishes":[{"name":"芋頭糕","desc":"蘭嶼芋頭糕，蘭嶼必吃特色小吃"}]},
    {"city":"台東","index":224,"dishes":[{"name":"客來吃樂","desc":"台東客來吃樂，台東人氣合菜餐廳"}]},
    {"city":"台東","index":226,"dishes":[{"name":"鬼頭刀美食","desc":"卡滋爾鬼頭刀特色美食，台東成功特色料理"}]},
    {"city":"台東","index":230,"dishes":[{"name":"石頭火鍋","desc":"新北斗石頭火鍋，台東人氣石頭火鍋"}]},
    {"city":"台東","index":231,"dishes":[{"name":"涮涮鍋","desc":"錢都日式涮涮鍋台東博愛店，台東人氣涮涮鍋"}]},
    {"city":"台東","index":232,"dishes":[{"name":"壽喜燒","desc":"牛比蔥壽喜燒專門店台東博愛店，台東人氣壽喜燒"}]},
    {"city":"台東","index":233,"dishes":[{"name":"火鍋","desc":"御饌鼎皇火鍋，台東人氣火鍋吃到飽"}]},
    {"city":"台東","index":234,"dishes":[{"name":"和牛燒烤","desc":"樂烤和牛台東店，台東燒烤吃到飽"}]},
    {"city":"台東","index":236,"dishes":[{"name":"山海產","desc":"808山海產店，台東海鮮人氣餐廳"}]},
    {"city":"台東","index":238,"dishes":[{"name":"人x人","desc":"人x人，台東特色合菜餐廳"}]},
    {"city":"台東","index":239,"dishes":[{"name":"時令料理","desc":"漁采時令料理更生店，台東新鮮海鮮料理"}]},
    {"city":"台東","index":242,"dishes":[{"name":"冰品","desc":"美濃冰品，台東人氣冰品店"}]},
    {"city":"台東","index":245,"dishes":[{"name":"麻糬","desc":"杉原陳家麻糬，台東必買伴手禮"}]},
    {"city":"台東","index":249,"dishes":[{"name":"豆花","desc":"台東古早味寶桑豆花，台東老牌豆花"}]},
    {"city":"台東","index":250,"dishes":[{"name":"青草茶","desc":"台東老東芳青草茶旗艦店，台東必喝青草茶"}]},
    {"city":"台東","index":256,"dishes":[{"name":"素食麵","desc":"蘇天助素食麵，台東人氣素食麵店"}]},
    {"city":"台東","index":263,"dishes":[{"name":"星星部落","desc":"星星部落景觀咖啡，台東鹿野高台觀星咖啡"}]},
    {"city":"台東","index":265,"dishes":[{"name":"花園咖啡","desc":"星龍花園咖啡，台東鹿野特色咖啡"}]},
    {"city":"台東","index":287,"dishes":[{"name":"客家菜","desc":"全家福客家菜館，台東老牌客家菜"}]},
    {"city":"台東","index":291,"dishes":[{"name":"旗魚料理","desc":"成功旗魚料理，台東成功必吃旗魚"}]},
    {"city":"台東","index":293,"dishes":[{"name":"鹿肉料理","desc":"綠島鹿肉料理，綠島特色鹿肉必吃"}]},
    {"city":"台東","index":294,"dishes":[{"name":"紅藜料理","desc":"七里坡紅藜養生料理，台東健康養生料理"}]},
    {"city":"台東","index":295,"dishes":[{"name":"旗魚","desc":"佳濱成功旗魚，台東成功旗魚料理必吃"}]},
    {"city":"台東","index":303,"dishes":[{"name":"小火鍋","desc":"億品鍋Mini Shabu Shabu台東店，台東人氣小火鍋"}]},
    {"city":"台東","index":306,"dishes":[{"name":"海景咖啡","desc":"可可娜咖啡，台東海景咖啡人氣店"}]},
    {"city":"台東","index":316,"dishes":[{"name":"牛排","desc":"小時厚牛排台東店，台東平價牛排"}]},
    {"city":"台東","index":317,"dishes":[{"name":"牛排","desc":"貴族世家台東店，台東老牌牛排連鎖"}]},
    {"city":"台東","index":327,"dishes":[{"name":"海鮮","desc":"欣逢平價海鮮，台東平價海鮮料理"}]},
    {"city":"台東","index":328,"dishes":[{"name":"越南美食","desc":"都蘭錦鸞越南美食Vietnam Food，台東都蘭異國料理"}]},
    {"city":"台東","index":330,"dishes":[{"name":"白榕樹","desc":"會走路的樹白榕樹，台東延平特色景觀"}]},
    {"city":"台東","index":331,"dishes":[{"name":"海鮮食堂","desc":"綠島非炒不可海鮮食堂，綠島必吃海鮮"}]},
    {"city":"台東","index":333,"dishes":[{"name":"蔥油餅","desc":"阿嬤的蔥油餅阿嬤的蔥Q餅，台東必吃蔥油餅"}]},
    {"city":"台東","index":334,"dishes":[{"name":"旅人咖啡","desc":"蘭嶼旅人Rover，蘭嶼特色咖啡旅人餐廳"}]},
    {"city":"台東","index":340,"dishes":[{"name":"日式料理","desc":"台東福井日式料理，台東人氣日式料理70分鐘"}]},
    {"city":"台東","index":348,"dishes":[{"name":"豆花","desc":"成功豆花，台東成功必吃豆花"}]},
    {"city":"台東","index":349,"dishes":[{"name":"三仙台小吃","desc":"成功三仙台周邊小吃，台東成功海鮮小吃"}]},
    {"city":"台東","index":352,"dishes":[{"name":"海產","desc":"宋媽媽海產店，台東成功海鮮必吃"}]},
    {"city":"台東","index":353,"dishes":[{"name":"海鮮","desc":"新澎湖海鮮餐廳，台東海鮮料理人氣店"}]},
    {"city":"台東","index":355,"dishes":[{"name":"麵食館","desc":"大陸婆婆麵食館，台東人氣麵食店"}]},
    {"city":"台東","index":357,"dishes":[{"name":"麵食","desc":"北平半畝園臺東，台東北方麵食人氣店"}]},
    {"city":"台東","index":358,"dishes":[{"name":"原味料理","desc":"萬家鄉原味料理，台東原住民風味料理"}]},
    {"city":"台東","index":360,"dishes":[{"name":"海鮮","desc":"拼經濟海鮮店，台東平價海鮮必吃"}]},
    {"city":"台東","index":363,"dishes":[{"name":"小吃部","desc":"開喜小吃部，台東人氣在地小吃"}]},
    {"city":"台東","index":364,"dishes":[{"name":"慧子的店","desc":"慧子的店，台東特色手工料理"}]},
    {"city":"台東","index":368,"dishes":[{"name":"蔥油餅","desc":"黃記蔥油餅海邊店，台東必吃蔥油餅"}]},
    {"city":"台東","index":369,"dishes":[{"name":"餃子館","desc":"南北餃子館，台東人氣餃子館"}]},
    {"city":"台東","index":374,"dishes":[{"name":"迴轉壽司","desc":"爭鮮迴轉壽司康達盛通台東店，台東人氣壽司"}]},
    {"city":"台東","index":378,"dishes":[{"name":"豬排","desc":"王子豬排，台東人氣日式豬排店"}]},
    {"city":"台東","index":381,"dishes":[{"name":"米故事館","desc":"多力米故事館，台東池上米專賣"}]},
    {"city":"台東","index":391,"dishes":[{"name":"大骨麵","desc":"哇哇哇大骨麵，台東特色大骨麵必吃"}]},
    {"city":"台東","index":392,"dishes":[{"name":"風味餐","desc":"正一茶園田媽媽傅姐風味餐，台東鹿野茶風味"}]},
    {"city":"台東","index":393,"dishes":[{"name":"大骨麵","desc":"鹿野大骨麵，台東鹿野必吃大骨麵"}]},
    {"city":"台東","index":394,"dishes":[{"name":"飯店料理","desc":"天龍飯店，台東知本溫泉飯店餐飲"}]},
    {"city":"台東","index":397,"dishes":[{"name":"南迴驛站","desc":"大武之心南迴驛站，台東大武特色驛站餐飲"}]},
    {"city":"台東","index":401,"dishes":[{"name":"我家小館","desc":"美樂地我家小館，台東人氣家常菜餐廳"}]},
    {"city":"台東","index":402,"dishes":[{"name":"滷肉飯","desc":"大眾滷肉飯中正店，台東人氣滷肉飯"}]},
    {"city":"台東","index":403,"dishes":[{"name":"牛肉麵","desc":"河腩味牛肉麵，台東人氣牛肉麵"}]},
    {"city":"台東","index":406,"dishes":[{"name":"水煎包","desc":"七里香水煎包，台東排隊水煎包"}]},
    {"city":"台東","index":409,"dishes":[{"name":"原住民美食","desc":"原始部落山地美食，台東原住民風味料理"}]},
    {"city":"台東","index":417,"dishes":[{"name":"日式豬排","desc":"蘭田手作日式豬排，台東人氣日式豬排"}]},
    {"city":"台東","index":419,"dishes":[{"name":"湯鍋","desc":"六扇門時尚湯鍋台東博愛店，台東平價鍋物"}]},
    {"city":"台東","index":421,"dishes":[{"name":"海產","desc":"台南七股海產店台東店，台東海鮮必吃"}]},
    {"city":"台東","index":422,"dishes":[{"name":"海產","desc":"特選海產店，台東人氣海產店"}]},
    {"city":"台東","index":425,"dishes":[{"name":"麻糬","desc":"陳記麻糬，台東必買伴手禮麻糬"}]},
    {"city":"台東","index":427,"dishes":[{"name":"蒸餃","desc":"鄰家蒸餃，台東人氣蒸餃店"}]},
    {"city":"台東","index":429,"dishes":[{"name":"早餐","desc":"早點大王，台東人氣排隊早餐"}]},
    {"city":"台東","index":449,"dishes":[{"name":"原住民音樂餐廳","desc":"響羅雷原住民音樂餐廳，台東特色音樂餐廳"}]},
    {"city":"台東","index":450,"dishes":[{"name":"景觀貨櫃","desc":"俩吆久景觀貨櫃，台東特色貨櫃景觀咖啡"}]},
    {"city":"台東","index":451,"dishes":[{"name":"原住民風味餐","desc":"九格浪原住民風味餐，台東原住民料理"}]},
    {"city":"台東","index":452,"dishes":[{"name":"部落音樂餐廳","desc":"雲棧部落音樂餐廳，台東特色音樂餐飲"}]},
    {"city":"台東","index":457,"dishes":[{"name":"茶餐廳","desc":"愛嬌姨茶餐廳，台東特色茶餐廳"}]},
    {"city":"台東","index":458,"dishes":[{"name":"布農部落","desc":"布農部落休閒農場，台東延平原住民體驗"}]},
    {"city":"台東","index":459,"dishes":[{"name":"漂流木餐廳","desc":"蘭嶼漂流木餐廳，蘭嶼特色餐廳必去"}]},
    {"city":"台東","index":464,"dishes":[{"name":"地瓜酥","desc":"楊記搖搖地瓜酥，台東必吃地瓜酥"}]},
    {"city":"台東","index":465,"dishes":[{"name":"早午餐","desc":"六吋盤早午餐台東新生店，台東人氣早午餐"}]},
    {"city":"台東","index":468,"dishes":[{"name":"海鮮","desc":"成功漁港海鮮餐廳，台東成功漁港新鮮海鮮"}]},
    {"city":"台東","index":469,"dishes":[{"name":"旗魚海味","desc":"旗遇海味，台東成功旗魚料理專賣"}]},
    {"city":"台東","index":475,"dishes":[{"name":"海產","desc":"美娥海產富岡，台東富岡漁港海鮮必吃"}]},
    {"city":"台東","index":477,"dishes":[{"name":"臭豆腐","desc":"久昂臭豆腐，台東人氣臭豆腐"}]},
    {"city":"台東","index":478,"dishes":[{"name":"丸八餐廳","desc":"丸八餐廳，台東老牌日式料理餐廳"}]},
    {"city":"台東","index":479,"dishes":[{"name":"早餐","desc":"中華早點台東市，台東中式早餐人氣店"}]},
    {"city":"台東","index":480,"dishes":[{"name":"糖廠冰","desc":"台東糖廠冰店，台東必吃糖廠冰品"}]},
    {"city":"台東","index":489,"dishes":[{"name":"渡假村","desc":"山水軒渡假村，台東知本渡假村餐飲"}]},
    {"city":"台東","index":494,"dishes":[{"name":"山地美食","desc":"米巴奈山地美食坊，台東原住民風味料理"}]},
    {"city":"台東","index":502,"dishes":[{"name":"早餐","desc":"明奎早餐店，台東排隊早餐名店"}]},
    {"city":"台東","index":503,"dishes":[{"name":"甕仔雞","desc":"海靖甕仔雞，台東必吃甕仔雞"}]},
    {"city":"台東","index":505,"dishes":[{"name":"冰城","desc":"津芳冰城，台東必吃古早味冰品"}]},
    {"city":"台東","index":511,"dishes":[{"name":"關山便當","desc":"源昌關山便當，台東關山必吃便當"}]},
    {"city":"台東","index":514,"dishes":[{"name":"休閒餐廳","desc":"麗荷園休閒餐廳，台東池上特色餐廳"}]},
    {"city":"台東","index":519,"dishes":[{"name":"海景咖啡","desc":"可可娜咖啡Coconut Cafe，台東海景咖啡人氣店"}]},
    {"city":"台東","index":525,"dishes":[{"name":"星咖啡","desc":"星咖啡，台東鹿野高台景觀咖啡"}]}
]

count = 0
for u in updates:
    city = u['city']
    idx = u['index']
    dishes = u['dishes']
    if city in data and idx < len(data[city]['food']):
        existing = data[city]['food'][idx].get('dishes', [])
        if not existing:
            data[city]['food'][idx]['dishes'] = dishes
            count += 1

with open('data-zh.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"Total updated: {count}")
print("Saved data-zh.json")