# -*- coding: utf-8 -*-
import json

with open('data-zh.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

# Batch 14 - remaining 雲林, 澎湖, 金馬
updates = [
    # === 雲林 remaining ===
    {"city":"雲林","index":8,"dishes":[{"name":"華山會館","desc":"華山會館，雲林古坑華山景觀餐廳"}]},
    {"city":"雲林","index":31,"dishes":[{"name":"花生酥","desc":"北港祥記花生酥，雲林北港百年老店伴手禮"}]},
    {"city":"雲林","index":34,"dishes":[{"name":"囍餅","desc":"北港臻狀元囍餅，雲林北港人氣囍餅"}]},
    {"city":"雲林","index":35,"dishes":[{"name":"飯館","desc":"黑先生飯館，雲林斗六人氣餐館現場候位"}]},
    {"city":"雲林","index":36,"dishes":[{"name":"窯烤雞","desc":"豪客窯烤雞斗六店，雲林烤雞串燒居酒屋"}]},
    {"city":"雲林","index":39,"dishes":[{"name":"火鍋","desc":"鍋道一號斗南旗艦店，雲林斗南高CP值火鍋"}]},
    {"city":"雲林","index":43,"dishes":[{"name":"日式鍋物","desc":"聚日式鍋物斗六鎮南店，雲林斗六人氣鍋物"}]},
    {"city":"雲林","index":44,"dishes":[{"name":"石頭火鍋","desc":"什浬鍋Shihli Stone Hot Pot，雲林特色石頭火鍋"}]},
    {"city":"雲林","index":80,"dishes":[{"name":"健康餐","desc":"青食，雲林斗六健康餐廳原型食材"}]},
    {"city":"雲林","index":82,"dishes":[{"name":"刈包","desc":"叁記傳食斗六創始店叁記刈包，雲林斗六人氣刈包"}]},
    {"city":"雲林","index":83,"dishes":[{"name":"韓式料理","desc":"韓楓館斗六店，雲林斗六韓式料理人氣店"}]},
    {"city":"雲林","index":86,"dishes":[{"name":"石頭火鍋","desc":"村上石頭火鍋虎尾店，雲林虎尾人氣火鍋"}]},
    {"city":"雲林","index":87,"dishes":[{"name":"古蹟餐飲","desc":"榕苑古蹟餐飲，雲林特色古蹟餐廳"}]},
    {"city":"雲林","index":88,"dishes":[{"name":"咖啡","desc":"迷樂卡啡斗南店，雲林斗南人氣咖啡廳"}]},
    {"city":"雲林","index":89,"dishes":[{"name":"咖啡","desc":"勝咖啡，雲林特色咖啡廳"}]},
    {"city":"雲林","index":91,"dishes":[{"name":"牛排","desc":"小兄弟牛排館，雲林虎尾平價牛排"}]},
    {"city":"雲林","index":92,"dishes":[{"name":"麻糬","desc":"幸福Mochi西螺麻糬延平老街店，雲林西螺必買"}]},
    {"city":"雲林","index":93,"dishes":[{"name":"鍋物","desc":"川玥秘境鍋物斗六店，雲林斗六家庭聚餐首選"}]},
    {"city":"雲林","index":94,"dishes":[{"name":"牛鍋物","desc":"雲鮮牛鍋物，雲林特色牛鍋物"}]},
    {"city":"雲林","index":95,"dishes":[{"name":"石頭涮涮鍋","desc":"養鍋Yang Guo石頭涮涮鍋斗六民生南店，雲林人氣鍋物"}]},
    {"city":"雲林","index":98,"dishes":[{"name":"燒肉","desc":"色鼎燒肉虎尾店，雲林虎尾人氣燒肉吃到飽"}]},
    {"city":"雲林","index":99,"dishes":[{"name":"麻辣鍋","desc":"饌鼎重慶麻辣鍋北港店，雲林北港麻辣火鍋"}]},
    {"city":"雲林","index":103,"dishes":[{"name":"咖啡農場","desc":"56號藍色公路咖啡廠水豚君羊駝，雲林特色動物咖啡農場"}]},
    {"city":"雲林","index":110,"dishes":[{"name":"燒肉","desc":"色鼎燒肉斗六店，雲林斗六超人氣燒肉"}]},
    {"city":"雲林","index":111,"dishes":[{"name":"麻辣鍋","desc":"小蒙牛頂級麻辣養生鍋斗六店，雲林斗六麻辣鍋"}]},
    {"city":"雲林","index":114,"dishes":[{"name":"拉麵","desc":"初八拉麵斗六店，雲林斗六人氣拉麵"}]},
    {"city":"雲林","index":138,"dishes":[{"name":"小火鍋","desc":"億品鍋虎尾店，雲林虎尾人氣小火鍋"}]},
    {"city":"雲林","index":147,"dishes":[{"name":"醬油博物館","desc":"西螺醬油博物館，雲林西螺必逛醬油觀光"}]},
    {"city":"雲林","index":148,"dishes":[{"name":"飯樂","desc":"樂飯樂販斗六店，雲林斗六人氣簡餐"}]},
    {"city":"雲林","index":149,"dishes":[{"name":"西式料理","desc":"雲品食坊西式複合式料理，雲林斗六西餐"}]},
    {"city":"雲林","index":151,"dishes":[{"name":"義國餐廳","desc":"Sunny Q陽光公主義國餐廳，雲林虎尾義大利麵"}]},
    {"city":"雲林","index":152,"dishes":[{"name":"複合式餐飲","desc":"幸福燈塔複合式餐飲雲林100碗，雲林特色複合式餐廳"}]},
    {"city":"雲林","index":153,"dishes":[{"name":"鴨肉麵","desc":"鴨丫小麵店北港美食，雲林北港在地必吃"}]},
    {"city":"雲林","index":156,"dishes":[{"name":"迴轉火鍋","desc":"嗨咿迴轉火鍋吃到飽，雲林斗六吃到飽火鍋"}]},
    {"city":"雲林","index":157,"dishes":[{"name":"火鍋","desc":"惹鍋虎尾店，雲林虎尾人氣火鍋"}]},
    {"city":"雲林","index":158,"dishes":[{"name":"升降鍋物","desc":"圓砌鴛鴦升降鍋物斗六旗艦店，雲林斗六特色鍋物"}]},
    {"city":"雲林","index":159,"dishes":[{"name":"火鍋","desc":"新千葉火鍋斗六店，雲林斗六高人氣火鍋"}]},
    {"city":"雲林","index":161,"dishes":[{"name":"火鍋","desc":"火鍋世家雲林虎尾店，雲林虎尾連鎖火鍋"}]},
    {"city":"雲林","index":162,"dishes":[{"name":"麻辣鍋","desc":"三國饌鴛鴦麻辣鍋虎尾中正旗艦店，雲林虎尾麻辣鍋"}]},
    {"city":"雲林","index":163,"dishes":[{"name":"鍋物","desc":"築間幸福鍋物雲林斗六店，雲林斗六人氣鍋物"}]},
    {"city":"雲林","index":166,"dishes":[{"name":"水產","desc":"武正水產餐廳，雲林海鮮餐廳週一公休"}]},
    {"city":"雲林","index":167,"dishes":[{"name":"活漁海鮮","desc":"斗六釣魚台活漁海鮮餐廳，雲林斗六在地美食推薦"}]},
    {"city":"雲林","index":175,"dishes":[{"name":"壽司","desc":"市場光壽司，雲林斗六人氣壽司店"}]},
    {"city":"雲林","index":176,"dishes":[{"name":"外帶壽司","desc":"一捲寿司全台第一外帶壽司品牌，雲林人氣壽司"}]},
    {"city":"雲林","index":178,"dishes":[{"name":"咖啡","desc":"嶼光Island雲林，雲林特色咖啡廳假日無預約"}]},
    {"city":"雲林","index":180,"dishes":[{"name":"恬恬","desc":"Immense恬恬，雲林斗六質感餐廳"}]},
    {"city":"雲林","index":181,"dishes":[{"name":"芋圓冰","desc":"濃喵手作芋圓嫩仙草剉冰燒仙草，雲林人氣冰品"}]},
    {"city":"雲林","index":183,"dishes":[{"name":"燒肉割烹","desc":"丸京燒肉割烹專門店斗六旗艦店，雲林斗六日式燒肉"}]},
    {"city":"雲林","index":184,"dishes":[{"name":"燒肉丼","desc":"宮本武丼直火燒肉丼斗六店，雲林斗六人氣丼飯"}]},
    {"city":"雲林","index":186,"dishes":[{"name":"牛排","desc":"史堤克牛排斗六店，雲林斗六牛排連鎖"}]},
    {"city":"雲林","index":188,"dishes":[{"name":"好客食堂","desc":"好客食堂，雲林人氣合菜餐廳"}]},
    {"city":"雲林","index":190,"dishes":[{"name":"地瓜球","desc":"虎尾地瓜球，雲林虎尾夜市必吃小吃"}]},
    {"city":"雲林","index":191,"dishes":[{"name":"素食","desc":"壹番素食餐廳斗六素食，雲林斗六素食餐廳"}]},
    {"city":"雲林","index":214,"dishes":[{"name":"台灣鯛","desc":"台灣鯛生態創意園區，雲林特色鯛魚料理"}]},
    {"city":"雲林","index":215,"dishes":[{"name":"狀元餅","desc":"二崙佳美狀元餅伍仁酥，雲林二崙必買伴手禮"}]},
    {"city":"雲林","index":229,"dishes":[{"name":"酸菜白肉鍋","desc":"劉家酸菜白肉鍋斗六店，雲林斗六人氣酸菜白肉鍋"}]},
    {"city":"雲林","index":230,"dishes":[{"name":"烹小鮮","desc":"烹小鮮麵館，雲林斗六人氣麵館"}]},
    {"city":"雲林","index":238,"dishes":[{"name":"咖啡","desc":"微樂生活咖啡，雲林特色咖啡廳"}]},
    {"city":"雲林","index":240,"dishes":[{"name":"秘境鍋物","desc":"野川堂秘境鍋物虎尾店，雲林虎尾人氣鍋物"}]},
    {"city":"雲林","index":241,"dishes":[{"name":"鍋物","desc":"築間幸福鍋物雲林虎尾店，雲林虎尾鍋物連鎖"}]},
    {"city":"雲林","index":242,"dishes":[{"name":"鍋物","desc":"五鮮級鍋物專賣雲林北港店，雲林北港火鍋"}]},
    {"city":"雲林","index":245,"dishes":[{"name":"咖啡","desc":"庵古坑咖啡，雲林古坑咖啡老店"}]},
    {"city":"雲林","index":253,"dishes":[{"name":"牛排","desc":"一鮮切炭燻牛排，雲林人氣牛排專賣"}]},
    {"city":"雲林","index":254,"dishes":[{"name":"羹","desc":"大娘羹檜意美食館，雲林特色羹料理"}]},
    {"city":"雲林","index":260,"dishes":[{"name":"美食旗艦店","desc":"深海深美食旗艦總店，雲林斗六海鮮餐廳"}]},
    {"city":"雲林","index":267,"dishes":[{"name":"黃金魚焿","desc":"三角窗黃金魚焿，雲林特色魚羹小吃"}]},
    {"city":"雲林","index":302,"dishes":[{"name":"第五大道","desc":"第五大道，雲林斗六人氣咖啡簡餐"}]},
    {"city":"雲林","index":306,"dishes":[{"name":"太陽月亮","desc":"一個太陽一個月亮，雲林特色景觀餐廳"}]},
    {"city":"雲林","index":307,"dishes":[{"name":"餐廚","desc":"CHICO餐廚，雲林斗六人氣西式餐廚"}]},
    {"city":"雲林","index":308,"dishes":[{"name":"迴轉壽司","desc":"侍悟丸迴轉壽司斗六店，雲林斗六人氣壽司"}]},
    {"city":"雲林","index":310,"dishes":[{"name":"懷舊料理","desc":"稻香村懷舊料理，雲林古早味合菜餐廳"}]},
    {"city":"雲林","index":316,"dishes":[{"name":"火鍋","desc":"肉多多火鍋雲林斗六店，雲林斗六人氣火鍋"}]},
    {"city":"雲林","index":317,"dishes":[{"name":"海鮮","desc":"八斗子海鮮餐廳，雲林海鮮合菜餐廳"}]},
    {"city":"雲林","index":322,"dishes":[{"name":"油飯麵線糊","desc":"阿豐油飯麵線糊，雲林北港必吃油飯"}]},
    {"city":"雲林","index":331,"dishes":[{"name":"冰店","desc":"曾記涼泉芳冰店，雲林古早味冰品"}]},
    {"city":"雲林","index":333,"dishes":[{"name":"燒肉","desc":"焰屋燒肉，雲林斗六人氣燒肉店"}]},
    {"city":"雲林","index":334,"dishes":[{"name":"無煙燒肉","desc":"夯石頭無煙燒肉斗六旗艦館，雲林斗六燒肉"}]},
    {"city":"雲林","index":335,"dishes":[{"name":"韓式火烤","desc":"江南大豬韓式火烤餐廳，雲林韓式料理"}]},
    {"city":"雲林","index":339,"dishes":[{"name":"牛排","desc":"喜樂牛排斗六店，雲林斗六平價牛排"}]},
    {"city":"雲林","index":354,"dishes":[{"name":"雲頂咖啡","desc":"雲頂咖啡，雲林古坑華山夜景咖啡"}]},
    {"city":"雲林","index":356,"dishes":[{"name":"虫二行館","desc":"華山觀止虫二行館，雲林古坑華山景觀餐廳"}]},
    {"city":"雲林","index":369,"dishes":[{"name":"高香珍","desc":"高香珍本店，雲林北港老牌糕餅店"}]},
    {"city":"雲林","index":375,"dishes":[{"name":"牛肉麵","desc":"老謝牛肉麵，雲林斗六人氣牛肉麵"}]},
    {"city":"雲林","index":377,"dishes":[{"name":"牛肉湯","desc":"北港輝煌牛肉湯，雲林北港必喝牛肉湯"}]},
    {"city":"雲林","index":385,"dishes":[{"name":"火雞肉飯","desc":"嘉義公園火雞肉飯，雲林嘉義style火雞肉飯"}]},
    {"city":"雲林","index":388,"dishes":[{"name":"鴨肉麵線","desc":"圓環阿明鴨肉麵線，雲林人氣鴨肉麵線"}]},
    {"city":"雲林","index":392,"dishes":[{"name":"老鄰居","desc":"老鄰居1971，雲林斗六懷舊餐廳"}]},
    {"city":"雲林","index":394,"dishes":[{"name":"日式料理","desc":"井野板前料理，雲林斗六日式料理"}]},
    {"city":"雲林","index":397,"dishes":[{"name":"飯湯","desc":"彭家飯湯，雲林特色飯湯必吃"}]},
    {"city":"雲林","index":400,"dishes":[{"name":"青松餐廳","desc":"青松餐廳，雲林合菜餐廳人氣"}]},
    {"city":"雲林","index":401,"dishes":[{"name":"煎盤粿","desc":"陳家煎盤粿，雲林北港特色煎盤粿"}]},
    {"city":"雲林","index":404,"dishes":[{"name":"夜景咖啡","desc":"好星晴夜景泡腳咖啡廳，雲林古坑夜景咖啡"}]},
    {"city":"雲林","index":405,"dishes":[{"name":"泡腳咖啡","desc":"華南天空之夜養生泡腳咖啡，雲林古坑華山泡腳"}]},
    {"city":"雲林","index":407,"dishes":[{"name":"牛肉料理","desc":"芸彰牧場牛肉料理餐廳，雲林斗南牛肉專賣"}]},
    {"city":"雲林","index":409,"dishes":[{"name":"麵攤","desc":"無名麵攤大胖麵攤，雲林斗六人氣麵攤"}]},
    {"city":"雲林","index":411,"dishes":[{"name":"火鍋","desc":"一品香火鍋斗六店，雲林斗六人氣火鍋"}]},
    {"city":"雲林","index":412,"dishes":[{"name":"石頭火鍋","desc":"誠石火鍋，雲林斗六石頭火鍋"}]},
    {"city":"雲林","index":413,"dishes":[{"name":"汕頭火鍋","desc":"老潮興汕頭火鍋熱烤串燒，雲林特色火鍋"}]},
    {"city":"雲林","index":415,"dishes":[{"name":"隨興咖啡","desc":"永光故事屋隨興沖咖啡，雲林特色咖啡廳"}]},
    {"city":"雲林","index":419,"dishes":[{"name":"日式料理","desc":"大東屋斗六棒球場旗艦店，雲林斗六日式料理"}]},
    {"city":"雲林","index":421,"dishes":[{"name":"冰店","desc":"溝仔垻清涼冰店，雲林古早味冰品必吃"}]},
    {"city":"雲林","index":424,"dishes":[{"name":"燒肉","desc":"炭火燒肉工房斗六店，雲林斗六炭火燒肉"}]},
    {"city":"雲林","index":427,"dishes":[{"name":"牛排","desc":"魔力牛牛排館虎尾店，雲林虎尾雙拼牛排"}]},
    {"city":"雲林","index":434,"dishes":[{"name":"香豆腐","desc":"大吉祥香豆腐虎尾店，雲林虎尾必吃臭豆腐"}]},
    {"city":"雲林","index":436,"dishes":[{"name":"香豆腐","desc":"大吉祥香豆腐虎尾店，雲林虎尾人氣豆腐"}]},
    {"city":"雲林","index":493,"dishes":[{"name":"咖啡","desc":"古坑荷苞山咖啡，雲林古坑咖啡發源地"}]},
    {"city":"雲林","index":494,"dishes":[{"name":"九層粿","desc":"黃記九層粿，雲林西螺必吃九層粿"}]},
    {"city":"雲林","index":499,"dishes":[{"name":"石斑魚火鍋","desc":"口湖龍膽石斑魚火鍋，雲林口湖特色魚火鍋"}]},
    {"city":"雲林","index":501,"dishes":[{"name":"庭園咖啡","desc":"雅砌庭園咖啡館，雲林古坑庭園咖啡"}]},
    {"city":"雲林","index":504,"dishes":[{"name":"土豆油飯","desc":"北港阿等土豆油飯，雲林北港必吃油飯"}]},
    {"city":"雲林","index":505,"dishes":[{"name":"北方麵食","desc":"東城北方麵食館，雲林北方麵食人氣店"}]},
    {"city":"雲林","index":507,"dishes":[{"name":"九層粿","desc":"西螺黃家九層粿，雲林西螺必吃九層粿"}]},
    {"city":"雲林","index":509,"dishes":[{"name":"火鍋","desc":"一品香火鍋虎尾店，雲林虎尾人氣火鍋"}]},
    {"city":"雲林","index":511,"dishes":[{"name":"湖畔咖啡","desc":"近水樓台湖畔森林咖啡，雲林古坑湖畔咖啡"}]},
    {"city":"雲林","index":512,"dishes":[{"name":"莊園咖啡","desc":"山妍慕夏莊園咖啡，雲林古坑莊園咖啡"}]},
    {"city":"雲林","index":513,"dishes":[{"name":"映象會館","desc":"桂林映象會館，雲林古坑景觀餐廳"}]},
    {"city":"雲林","index":530,"dishes":[{"name":"無煙燒肉","desc":"夯石頭無煙燒肉虎尾旗艦館，雲林虎尾燒肉"}]},
    {"city":"雲林","index":540,"dishes":[{"name":"香豆腐","desc":"大吉祥香豆腐斗六店，雲林斗六必吃豆腐"}]},
    {"city":"雲林","index":554,"dishes":[{"name":"陽春麵臭豆腐","desc":"文元街陽春麵臭豆腐，雲林虎尾必吃"}]},
    {"city":"雲林","index":555,"dishes":[{"name":"文化園區","desc":"他里霧文化園區，雲林斗南文化景點"}]},
    {"city":"雲林","index":558,"dishes":[{"name":"牛樂園","desc":"千巧谷牛樂園牧場，雲林虎尾超大牧場餐廳"}]},
    {"city":"雲林","index":560,"dishes":[{"name":"巴登咖啡","desc":"巴登咖啡，雲林古坑老牌咖啡店"}]},
    {"city":"雲林","index":561,"dishes":[{"name":"素食","desc":"16號廚房素食餐廳斗六店，雲林斗六素食餐廳"}]},
    {"city":"雲林","index":578,"dishes":[{"name":"羊肉爐","desc":"日日興現宰羊肉爐，雲林虎尾必吃羊肉爐"}]},
    {"city":"雲林","index":579,"dishes":[{"name":"肉圓","desc":"阿火肉圓，雲林北港必吃肉圓"}]},
    {"city":"雲林","index":587,"dishes":[{"name":"羊肉","desc":"東市羊肉，雲林虎尾人氣羊肉料理"}]},
    {"city":"雲林","index":591,"dishes":[{"name":"鴨肉麵線","desc":"阿海師鴨肉麵線，雲林必吃鴨肉麵線"}]},
    {"city":"雲林","index":594,"dishes":[{"name":"當歸鴨","desc":"虎尾王家當歸鴨麵線，雲林虎尾人氣當歸鴨"}]},
    {"city":"雲林","index":595,"dishes":[{"name":"肉羹","desc":"阿世香菇肉羹，雲林人氣肉羹店"}]},
    {"city":"雲林","index":597,"dishes":[{"name":"庭園咖啡","desc":"古坑啡你不可庭園咖啡，雲林古坑庭園咖啡"}]},
    {"city":"雲林","index":599,"dishes":[{"name":"桃花源","desc":"桃花源餐廳，雲林合菜餐廳人氣"}]},
    {"city":"雲林","index":606,"dishes":[{"name":"庭園餐廳","desc":"左岸101庭園餐廳，雲林古坑庭園合菜"}]},
    {"city":"雲林","index":607,"dishes":[{"name":"湯鍋","desc":"六扇門時尚湯鍋虎尾中正店，雲林虎尾平價鍋物"}]},
    {"city":"雲林","index":609,"dishes":[{"name":"海鮮","desc":"海村澎湖活海鮮餐廳，雲林澎湖海鮮料理"}]},
    {"city":"雲林","index":612,"dishes":[{"name":"咖啡館","desc":"凹凸咖啡館，雲林斗六特色咖啡館"}]},
    {"city":"雲林","index":615,"dishes":[{"name":"庭園咖啡","desc":"啡你不可庭園咖啡廳，雲林古坑庭園咖啡"}]},
    {"city":"雲林","index":617,"dishes":[{"name":"當歸鴨","desc":"圓環當歸鴨，雲林北港人氣當歸鴨"}]},
    {"city":"雲林","index":620,"dishes":[{"name":"壽司","desc":"スシロー壽司郎雲林斗六店，雲林斗六人氣迴轉壽司"}]},
    {"city":"雲林","index":623,"dishes":[{"name":"菓寮","desc":"虎珍堂菓寮店，雲林虎尾必買伴手禮"}]},
    {"city":"雲林","index":624,"dishes":[{"name":"燒肉","desc":"官東燒肉斗六店，雲林斗六燒肉餐廳"}]},
    {"city":"雲林","index":625,"dishes":[{"name":"韓式烤肉","desc":"豬烤官韓式烤肉吃到飽虎尾店，雲林虎尾烤肉"}]},
    {"city":"雲林","index":628,"dishes":[{"name":"牛排","desc":"成功牛排斗六店，雲林斗六平價牛排"}]},
    {"city":"雲林","index":631,"dishes":[{"name":"當歸鴨","desc":"虎尾王家當歸鴨肉麵線，雲林虎尾必吃"}]},
    {"city":"雲林","index":660,"dishes":[{"name":"煙燻鵝肉","desc":"福記煙燻鵝肉，雲林必吃煙燻鵝肉"}]},
    {"city":"雲林","index":661,"dishes":[{"name":"魷魚羹麵","desc":"虎尾魷魚羹麵，雲林虎尾人氣魷魚羹"}]},
    {"city":"雲林","index":668,"dishes":[{"name":"圓仔湯","desc":"北港圓仔湯，雲林北港必吃甜品"}]},
    {"city":"雲林","index":676,"dishes":[{"name":"美食廣場","desc":"雲林溪美食廣場，雲林斗六人氣美食街"}]},
    {"city":"雲林","index":677,"dishes":[{"name":"活海鮮","desc":"廟口活海鮮餐廳，雲林海鮮合菜餐廳"}]},
    {"city":"雲林","index":680,"dishes":[{"name":"韓式烤肉","desc":"豬烤官韓式烤肉吃到飽斗南店，雲林斗南烤肉"}]},
    {"city":"雲林","index":693,"dishes":[{"name":"仙地咖啡","desc":"仙地咖啡，雲林古坑華山景觀咖啡"}]},
    {"city":"雲林","index":713,"dishes":[{"name":"馬蹄蛤","desc":"口湖馬蹄蛤主題館，雲林口湖特色水產體驗"}]},
    {"city":"雲林","index":717,"dishes":[{"name":"休閒農莊","desc":"米多力休閒農莊，雲林休閒農場餐廳"}]},
    {"city":"雲林","index":720,"dishes":[{"name":"熱炒","desc":"萬八自助式熱炒，雲林平價熱炒吃到飽"}]},
    {"city":"雲林","index":723,"dishes":[{"name":"花枝鱔魚麵","desc":"怪人花枝鱔魚麵雲林100碗，雲林特色麵食"}]},
    {"city":"雲林","index":727,"dishes":[{"name":"農稼莊","desc":"農稼莊古早味餐廳，雲林古早味合菜"}]},
    {"city":"雲林","index":744,"dishes":[{"name":"餅行","desc":"永光餅行西點麵包，雲林北港老牌餅店"}]},
    {"city":"雲林","index":746,"dishes":[{"name":"田園小館","desc":"田園小館，雲林古早味餐廳"}]},
    {"city":"雲林","index":758,"dishes":[{"name":"茶園","desc":"嘉義梅山二尖山休閒茶園，雲林梅山茶園"}]},
    {"city":"雲林","index":683,"dishes":[{"name":"客家菜","desc":"老地方客家菜大溪超人氣美食，雲林道地老店"}]},
    {"city":"雲林","index":451,"dishes":[{"name":"夜景泡腳","desc":"好星晴夜景泡腳咖啡廳，雲林古坑華山夜景咖啡"}]},
    {"city":"雲林","index":452,"dishes":[{"name":"泡腳咖啡","desc":"華南天空之夜養生泡腳咖啡，雲林華山泡腳咖啡"}]},
    
    # === 澎湖 remaining ===
    {"city":"澎湖","index":1,"dishes":[{"name":"海鮮料理","desc":"潮境TideLand海鮮料理，澎湖精緻海鮮餐廳"}]},
    {"city":"澎湖","index":3,"dishes":[{"name":"海鮮","desc":"龍門海鮮，澎湖龍門新鮮海鮮料理"}]},
    {"city":"澎湖","index":9,"dishes":[{"name":"小卷麵線","desc":"吉貝小三的店小卷麵線米粉綜合仙草冰，澎湖吉貝必吃"}]},
    {"city":"澎湖","index":18,"dishes":[{"name":"麵猴","desc":"外婆麵猴，澎湖特色古早味麵食"}]},
    {"city":"澎湖","index":19,"dishes":[{"name":"海鮮","desc":"海鱻，澎湖新鮮海鮮料理人氣店"}]},
    {"city":"澎湖","index":22,"dishes":[{"name":"麻辣鍋","desc":"巴適麻辣鍋，澎湖馬公人氣麻辣鍋"}]},
    {"city":"澎湖","index":24,"dishes":[{"name":"鍋物","desc":"擄胃食堂個人精致鍋物，澎湖精緻個人鍋物"}]},
    {"city":"澎湖","index":33,"dishes":[{"name":"番茄農場","desc":"兩個番茄農場，澎湖特色番茄料理"}]},
    {"city":"澎湖","index":42,"dishes":[{"name":"花火節餐廳","desc":"雛菊見DAISY HOUSE澎湖店，澎湖花火節聚餐美食"}]},
    {"city":"澎湖","index":45,"dishes":[{"name":"麻辣鍋","desc":"新巴適經典麻辣鍋澎湖店，澎湖馬公麻辣鍋"}]},
    {"city":"澎湖","index":50,"dishes":[{"name":"海禮","desc":"嶼蘊海禮，澎湖特色伴手禮餐飲"}]},
    {"city":"澎湖","index":53,"dishes":[{"name":"小料理","desc":"漁師小料理，澎湖馬公日式小料理"}]},
    {"city":"澎湖","index":62,"dishes":[{"name":"日式料理","desc":"海童日式料理，澎湖馬公人氣日式料理"}]},
    {"city":"澎湖","index":66,"dishes":[{"name":"火鍋","desc":"金醬府，澎湖馬公火鍋餐廳"}]},
    {"city":"澎湖","index":68,"dishes":[{"name":"個人燒肉","desc":"栄次郎個人燒肉澎湖馬公店，澎湖馬公燒肉"}]},
    {"city":"澎湖","index":91,"dishes":[{"name":"癮餐廳","desc":"Addict restaurant癮餐廳，澎湖馬公特色餐廳"}]},
    {"city":"澎湖","index":92,"dishes":[{"name":"燒烤","desc":"友先燒烤海陸自助式室內冷氣燒烤，澎湖烤蚵專場"}]},
    {"city":"澎湖","index":93,"dishes":[{"name":"披薩","desc":"瑪咖朵披薩Mercato Pizza，澎湖馬公手工披薩"}]},
    {"city":"澎湖","index":94,"dishes":[{"name":"炸粿","desc":"洪家炸粿，澎湖馬公必吃炸粿"}]},
    {"city":"澎湖","index":95,"dishes":[{"name":"小吃","desc":"富園小吃，澎湖馬公平價小吃"}]},
    {"city":"澎湖","index":97,"dishes":[{"name":"海鮮","desc":"668海鮮餐廳，澎湖海鮮餐廳人氣"}]},
    {"city":"澎湖","index":99,"dishes":[{"name":"餡餅","desc":"澎湖老家餡餅，澎湖馬公必吃餡餅"}]},
    {"city":"澎湖","index":107,"dishes":[{"name":"宵夜早午餐","desc":"朝食暮饗澎湖宵夜早午餐，澎湖深夜美食"}]},
    {"city":"澎湖","index":110,"dishes":[{"name":"食品","desc":"御品家食品，澎湖伴手禮必買"}]},
    {"city":"澎湖","index":113,"dishes":[{"name":"燒烤吃到飽","desc":"澎島之星燒烤吃到飽，澎湖馬公燒烤"}]},
    {"city":"澎湖","index":118,"dishes":[{"name":"餐廳","desc":"吉貝別野餐廳，澎湖吉貝島餐廳"}]},
    {"city":"澎湖","index":129,"dishes":[{"name":"紫菜冬粉","desc":"清峰海鮮紫菜冬粉，澎湖特色紫菜冬粉"}]},
    {"city":"澎湖","index":134,"dishes":[{"name":"壽司鍋物","desc":"澎漁海味壽司鍋物草屯店，澎湖海味壽司"}]},
    {"city":"澎湖","index":135,"dishes":[{"name":"活海鮮","desc":"珍海味活海鮮，澎湖馬公活海鮮"}]},
    {"city":"澎湖","index":149,"dishes":[{"name":"烘焙餐館","desc":"沃德先生烘焙餐館，澎湖馬公烘焙餐廳"}]},
    {"city":"澎湖","index":154,"dishes":[{"name":"客家小館","desc":"糧園茶藝客家小館，澎湖客家料理"}]},
    {"city":"澎湖","index":156,"dishes":[{"name":"海鮮合菜","desc":"澎漁宴生猛海鮮，澎湖必吃海鮮合菜"}]},
    {"city":"澎湖","index":161,"dishes":[{"name":"食堂","desc":"西河食堂，澎湖馬公特色食堂"}]},
    {"city":"澎湖","index":162,"dishes":[{"name":"活海鮮","desc":"華珍活海鮮，澎湖馬公平價活海鮮"}]},
    {"city":"澎湖","index":167,"dishes":[{"name":"海鮮餐廳","desc":"海九澎湖海鮮餐廳，澎湖馬公海鮮必吃"}]},
    {"city":"澎湖","index":168,"dishes":[{"name":"咖啡館","desc":"及林春咖啡館，澎湖馬公特色咖啡廳"}]},
    {"city":"澎湖","index":173,"dishes":[{"name":"仙草","desc":"紫玉仙草，澎湖馬公人氣仙草"}]},
    {"city":"澎湖","index":176,"dishes":[{"name":"碳烤","desc":"澎湖山水夏日碳烤，澎湖山水沙灘碳烤"}]},
    {"city":"澎湖","index":193,"dishes":[{"name":"番茄農場","desc":"兩個番茄農場，澎湖特色番茄料理"}]},
    {"city":"澎湖","index":196,"dishes":[{"name":"購物廣場","desc":"澎坊購物休閒廣場，澎湖馬公免稅購物"}]},
    {"city":"澎湖","index":199,"dishes":[{"name":"海鮮","desc":"阿東海鮮餐廳，澎湖馬公海鮮料理"}]},
    {"city":"澎湖","index":200,"dishes":[{"name":"特色餐廳","desc":"鹹水煙澎湖特色餐廳，澎湖特色料理"}]},
    {"city":"澎湖","index":201,"dishes":[{"name":"合菜","desc":"日新餐廳，澎湖馬公老牌合菜"}]},
    {"city":"澎湖","index":205,"dishes":[{"name":"刈包早餐","desc":"外垵刈包福氣早餐店，澎湖西嶼必吃早餐"}]},
    {"city":"澎湖","index":209,"dishes":[{"name":"雞排","desc":"澎湖三哥雞排三多店，澎湖馬公人氣雞排"}]},
    {"city":"澎湖","index":215,"dishes":[{"name":"我家小館","desc":"美樂地我家小館，澎湖馬公家常菜"}]},
    {"city":"澎湖","index":220,"dishes":[{"name":"漁港麵店","desc":"澎湖漁港麵店，澎湖漁港小吃必吃"}]},
    {"city":"澎湖","index":221,"dishes":[{"name":"燒餅","desc":"鐘記燒餅，澎湖馬公必吃燒餅"}]},
    {"city":"澎湖","index":224,"dishes":[{"name":"小管麵線","desc":"小萍的店小管麵線，澎湖必吃小管麵線"}]},
    {"city":"澎湖","index":225,"dishes":[{"name":"炸粿鯊魚排","desc":"大池炸粿鯊魚排，澎湖必吃炸物"}]},
    {"city":"澎湖","index":238,"dishes":[{"name":"龍星餐廳","desc":"龍星餐廳，澎湖馬公海鮮合菜"}]},
    {"city":"澎湖","index":242,"dishes":[{"name":"田媽媽","desc":"星月灣田媽媽餐廳，澎湖特色合菜"}]},
    {"city":"澎湖","index":253,"dishes":[{"name":"燒烤牡蠣","desc":"澎湖瘋燒烤新鮮牡蠣每日產地直送，澎湖烤蚵"}]},
    {"city":"澎湖","index":256,"dishes":[{"name":"燒肉飯","desc":"城隍廟前燒肉飯，澎湖馬公必吃燒肉飯"}]},
    {"city":"澎湖","index":263,"dishes":[{"name":"觀光工廠","desc":"媽宮食品觀光工廠，澎湖馬宮伴手禮"}]},
    {"city":"澎湖","index":264,"dishes":[{"name":"蒸鍋海鮮","desc":"鮮食堂海鮮蒸鍋，澎湖第一家蒸鍋海鮮"}]},
    {"city":"澎湖","index":266,"dishes":[{"name":"漁村海鮮","desc":"阿華漁村海鮮料理，澎湖漁村海鮮必吃"}]},
    {"city":"澎湖","index":272,"dishes":[{"name":"公園咖啡","desc":"林投公園咖啡，澎湖林投公園景觀咖啡"}]},
    {"city":"澎湖","index":274,"dishes":[{"name":"巷咖啡","desc":"肇林巷咖啡，澎湖馬公特色咖啡廳"}]},
    {"city":"澎湖","index":275,"dishes":[{"name":"漁村咖啡","desc":"阿華咖啡，澎湖漁村特色咖啡"}]},

    # === 金馬 remaining ===
    {"city":"金馬","index":4,"dishes":[{"name":"甜點","desc":"愜意甜點工作室金門甜點伴手禮，金門人氣甜點"}]},
    {"city":"金馬","index":26,"dishes":[{"name":"飯店","desc":"海福花園飯店，金馬馬祖人氣飯店餐飲"}]},
    {"city":"金馬","index":27,"dishes":[{"name":"冰菓室","desc":"嘉年華冰菓室，金馬馬祖必吃冰品"}]},
    {"city":"金馬","index":31,"dishes":[{"name":"戰地滋味","desc":"雨川食堂金門戰地滋味，金門特色戰地風味料理"}]},
    {"city":"金馬","index":35,"dishes":[{"name":"蝦寮食堂","desc":"蝦寮食堂，金馬馬祖特色海鮮食堂"}]},
    {"city":"金馬","index":53,"dishes":[{"name":"老街","desc":"陽翟老街軍中樂園拍攝場景，金馬馬祖特色景點"}]},
    {"city":"金馬","index":63,"dishes":[{"name":"廣東粥","desc":"聯成廣東粥，金門人氣廣東粥"}]},
    {"city":"金馬","index":66,"dishes":[{"name":"老街","desc":"沙美老街，金門金沙老街必逛"}]},
    {"city":"金馬","index":83,"dishes":[{"name":"大眾飲食","desc":"馬港大眾飲食店，金馬馬祖人氣家常菜"}]},
    {"city":"金馬","index":90,"dishes":[{"name":"芹壁咖啡","desc":"芹壁咖啡，金馬馬祖芹壁村海景咖啡"}]}
]

count = 0
for u in updates:
    city = u['city']
    idx = u['index']
    dishes = u['dishes']
    if city in data and idx < len(data[city]['food']):
        existing = data[city]['food'][idx].get('dishes', [])
        if not existing:
            data[city]['food'][idx]['dishes'] = dishes
            count += 1

with open('data-zh.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"Total updated: {count}")
print("Saved data-zh.json")